<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.

// Removes Skip Links.
remove_action( 'genesis_before_header', 'genesis_skip_links', 5 );

add_action( 'wp_enqueue_scripts', 'genesis_sample_dequeue_skip_links' );
/**
 * Dequeues Skip Links Script.
 *
 * @since 1.0.0
 */
function genesis_sample_dequeue_skip_links() {

	wp_dequeue_script( 'skip-links' );

}

/* Add ACF Page Header */
//add_action( 'genesis_before_loop', 'gs_page_header' );

// Removes site header elements.
//remove_action( 'genesis_header', 'genesis_do_header' );

// Removes navigation.
//remove_theme_support( 'genesis-menus' );

// Removes div.site-inner's div.wrap
add_filter( 'genesis_structural_wrap-site-inner', '__return_empty_' );

// Removes site footer elements.
//remove_action( 'genesis_footer', 'genesis_footer_markup_open', 5 );
remove_action( 'genesis_footer', 'genesis_do_footer' );
//remove_action( 'genesis_footer', 'genesis_footer_markup_close', 15 );
remove_action( 'genesis_entry_content', 'genesis_entry_content', 5 );
remove_action( 'genesis_entry_header', 'genesis_do_post_title' );
remove_action( 'genesis_entry_content', 'genesis_do_post_content' );


//remove side navigation
remove_action( 'genesis_sidebar', 'genesis_do_sidebar' );
unregister_sidebar( 'sidebar' );


add_action( 'genesis_entry_content', 'single_content' );
function single_content(){
    ?>
<div class="single_post_content">
<div class="container">
    <div class="row">
        <div class="col-lg-8 single_post_content__text">
            <?php the_content(); ?>
        </div>
        <div class="col-lg-4 sidebar_like_col">
            <?php 
            if(is_singular('services')){ ?>
            <div class="single_post_content__sidebar">
                <div class="service_form">
                    <div class="service_form__media">
                        <?php
                        $post_id = get_the_ID();
                        $featuredTitle = get_the_title();
                        $feat_image = wp_get_attachment_url(get_post_thumbnail_id($post_id));
                        $img_feat = !empty($feat_image)?sprintf('<img src="%s" alt="%s" />', $feat_image, "Image of ".$featuredTitle):'';
                        echo $img_feat;
                        ?>
                    </div>
                    <div class="service_form_content">
                        <?php echo get_form_shortcode(); ?>
                    </div>
                </div>
            </div>
            <?php }else{ ?>
            <div class="single_blogpost_content__sidebar">
                <?php echo dynamic_sidebar( 'blog_sidebar' ); ?>
            </div>    
            <?php } ?>
        </div>
    </div>
</div>
</div>
<?php

if(is_singular('post')){
    ?>
<div class="">
    <?php  display_blog_grid_block(
                array(
                    'title' =>  'Related Posts',
                'sub_title' =>  'INSIGHTS',
                'description' =>  '',
                'show_view_all_button' =>  true,
                'show_insight_only' =>  true,
                'talk_to_us' =>  false,
                'talk_to_us_link' =>  '', 
                'show_filter' =>  false,
                'show_pagination' =>  false,
                'limit' =>  '4', 
                'content_block_settings' => array(
                    'background-color' =>  '#b5d7f4',
                    'background-image' =>  false,
                    'spacing-top' =>  'medium',
                    'section_style_type' =>  'light',
                    'background-position' =>  'bottom left',
                    'background-size' =>  '60%',
                    'background-repeat' =>  false
                )
                )
            ); ?>
</div>
    <?php
}

}
genesis(); ?>